main: be.griffinbabe.webauctionhouse.Main
name: WebAuctionHouse
version: 1.0
author: GriffinBabe
description: Minecraft auction house with website support
commands:
  wahhelp:
    description: Help pages for WebAuctionHouse plugin
    usage: /wahhelp
    permission: webauctionhouse.help
    permission-message: You don't have the webauctionhouse.help permission.
  wahresetdb:
    description: Resets the databse of the plugin.
    usage: /wahresetdb
    permission: webauctionhouse.resetdb
    permission-message: You don't have the webauctionhouse.resetdb permission.